### ISSUE TITLE
Chapter02: LogGauss error

### ISSUE THREAD

**Issue by tndoan** [PRML/PRMLT#34]
There are some errors in ```logGauss.m```

```matlab
 X = [1 2 4.0]; mu = 1; sigma=2
logGauss(X, mu, sigma)
```

The result is 
```matlab
   -1.2655   -1.5155   -3.5155
```

while using the build-in function ```normpdf``` provides a different result
```matlab
normpdf(X, mu, sigma)

ans =

    0.1760    0.1995    0.1210
```

**Comment by sth4nth** [comment]
logGauss requires variance, where normpdf requies standard deviation. Therefore you should compare
exp(logGauss(X,mu,sigma^2)) with normpdf(X,mu,sigma)
