### ISSUE TITLE
Possible error in formula 10.63

### ISSUE THREAD

**Issue by tguillemot** [PRML/PRMLT#35]
Hello, I have inspected the code :
https://github.com/PRML/PRMLT/blob/master/chapter10/mixGaussVb.m#L67
But it seems that is not correspond to equation 10.63 :
```v = v0 + nk``` -> ```v = v0 + nk + 1```
I haven't seen à typos on that on the Bishop' website.
Could you confirm please ?
Thanks in advance

**Comment by sth4nth** [comment]
yes, this is intended. I believe that this is a error of the book from my own derivation.

**Comment by tguillemot** [comment]
@sth4nth Thanks :+1:

**Comment by sth4nth** [comment]
@tguillemot I have rechecked the PRML book and cross checked MLAPP that both books wrote this part as v = v0 + nk + 1. However, for a conjugate Gaussian, the posterior should have v=v0+n, which results in a contradiction. Now I am not very confident which one should be used here. 

However, from a practical perspective, they make little difference, the difference is really only a different prior v0. But I still hope someone could explain to me where the "+1" comes from.
