### ISSUE TITLE
Label output from logitBin.m seems inverted

### ISSUE THREAD

**Issue by erikrtn** [PRML/PRMLT#36]
Hi Mo,

First, thanks so much for your efforts here.

I want to ask if there is a problem with [`logitBinPred.m`](https://github.com/PRML/PRMLT/blob/master/chapter04/logitBinPred.m). Output seems inverted (i.e. 0 should be 1, and 1 should be 0).

I need to delve further into the script itself, but please run [this test script](https://github.com/erikrtn/misc_matlab/blob/master/test_prmlt_logreg.m) as an illustrative example.

I create a vector of labels, and features that are linearly related to the labels.

The logistic regression should be able to easily classify these features; I've confirmed with MATLAB built-in functions and other tools like libsvm.

If I invert the output from [`logitBinPred.m`](https://github.com/PRML/PRMLT/blob/master/chapter04/logitBinPred.m), the performance dramatically improves to expected levels.

Am I missing something? I'll explore your script more.

Thanks.

**Comment by erikrtn** [comment]
I found a fix and submitted a pull request.

**Comment by sth4nth** [comment]
fixed. Thanks for reporting.

**Comment by sth4nth** [comment]
@erikrtn thanks for the bug report. log1pexp(x) is a numerical stable version of log(1+exp(x)). So the fix for the bug you reported should be 
-p = exp(-log1pexp(w'X)); 
+p = exp(-log1pexp(-w'X));
