### ISSUE TITLE
Chapter 7: Use similar data as demo, but not work

### ISSUE THREAD

**Issue by so2liu** [PRML/PRMLT#47]
Hallo, thank you for your all efforts. 
Recently I met a problem for `remBinFp` function. I used my data with size 2*1000 and label with 1*1000. But something happened and the output `model.index` is 3, while in your demo it's 3. Therefore, `binPlot` func doesn't work. 
Could you please take a look for me? I upload the [data.mat](https://drive.google.com/open?id=1F0eMKCjiIYGbgmpXLgYIrdJi7_mIlE8k) in google drive. Thanks

```
%% RVM for classification
load('data.mat');
[model, llh] = rvmBinFp(X, y);
plot(llh);
y = rvmBinPred(model,X)+1;
figure;
binPlot(model,X,y);
---------------------
Index exceeds matrix dimensions.

Error in binPlot (line 25)
y = w(1)*x1+w(2)*x2+w(3);
```

**Comment by sth4nth** [comment]
I am not able to download your data now. Could you upload your data to some place inside GFW.

**Comment by sth4nth** [comment]
For the binary classifier, the labels are assumed to be (0/1), where as the labels your data are (1/2)

**Comment by sth4nth** [comment]
There is indeed a problem that the binPlot function does not support sparse models. Fixed

**Comment by sth4nth** [comment]
There is indeed a problem that the binPlot function does not support sparse models. Fixed to use plotClass instead.
