### ISSUE TITLE
Shouldn't there be biases in the example from Chapter 5?

### ISSUE THREAD

**Issue by MisterTellini** [PRML/PRMLT#48]
I am currently unable to make it work for a regression problem. Your example (a classification problem) runs well for me, but I wonder if shouldn't it have biases for increased performance as the book recommends.
Thank you in advance, and best regards!

**Comment by sth4nth** [comment]
You are right. It should have biases. I was just being lazy. Will fix it.

**Comment by sth4nth** [comment]
Fixed
